name: ${DOCKER_NAME}
services:
  mongodb:
    image: "mongo:7-jammy"
    environment:
      - PUID=1000
      - PGID=1000
      - NAME_ENV=${NAME:-trung}
    volumes:
      - ${VOLUME_DB_PATH:-db}:/data/db
    
volumes:
  # These named volumes are used when custom volume paths are not specified
  # If VOLUME_*_PATH variables are set, these volumes will be ignored
  db:
  elastic:
  files:
